############################
# VARIABLES GLOBALES
############################
variables:
  GIT_DEPTH: "1"
  SONAR_HOST_URL: "http://192.168.1.200:9000"
  REGISTRY_URL: "registry.gitlab.com"
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository --batch-mode"
  DOCKER_DRIVER: overlay2
############################
# CACHE
############################
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - frontend/node_modules/

############################
# STAGES
############################
default:
  image: maven:3.8.5-openjdk-17
stages:
  - build-shared
  - build-all
  - test-unitaires
  - security-scan
  - policy-check 
  - docker-build
  - docker-scan
  - deploy-cloud 
  - dast-scan
  - upload-defectdojo

############################
# 1️⃣ INSTALLATION DES MODULES COMMUNS
############################
install-commons:
  stage: build-shared
  tags:
     - vm
  image: maven:3.8.5-openjdk-17
  script:
    - cd backend/common-service && mvn install -DskipTests $MAVEN_CLI_OPTS
    - cd ../common-student && mvn install -DskipTests $MAVEN_CLI_OPTS
    - cd ../common-exam && mvn install -DskipTests $MAVEN_CLI_OPTS
############################
# 2️⃣ BUILD GLOBAL DU BACKEND (Génération des JARs)
############################
build-all-backend:
  stage: build-all
  tags:
     - vm
  image: maven:3.8.5-openjdk-17
  needs: ["install-commons"]
  script:
    - cd backend
    - |
      for service in answer-service api-gateway-service course-service exam-service user-service eureka-service ; do
        echo "🔨 Compilation de $service..."
        cd $service && mvn package -DskipTests $MAVEN_CLI_OPTS && cd ..
      done
  artifacts:
    paths:
      - "backend/*/target/*.jar"
    expire_in: 2 hours
  

############################
# 3️⃣ BUILD DU FRONTEND (Compilation Angular)
############################
build-frontend-app:
  stage: build-all
  tags:
     - vm
  image: node:18-alpine
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npm run build -- --configuration production || echo "Build failed but continuing for demo"
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 2 hours
  

############################
# 2️⃣ TESTS BACKEND + JACOCO
############################
backend-tests:
  stage: test-unitaires
  tags:
     - vm
  image: maven:3.8.5-openjdk-17
  needs: ["install-commons","build-all-backend"]
  script: |
    cd backend
    for service in answer-service api-gateway-service course-service exam-service user-service eureka-service; do
      echo "========== Testing $service =========="
      cd $service
      mvn test $MAVEN_CLI_OPTS -Dspring.profiles.active=test
      cd ..
    done
  artifacts:
    when: always
    paths:
      - backend/**/target/classes
      - backend/**/target/site/jacoco/jacoco.xml
    expire_in: 1 hour
  

############################
# 3️⃣ TESTS FRONTEND (ANGULAR)
############################
frontend-tests:
  stage: test-unitaires
  tags:
     - vm
  image: node:18-alpine
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - npm run test -- --coverage --watchAll=false || true
  artifacts:
    when: always
    paths:
      - frontend/coverage/lcov.info
    expire_in: 1 hour
  allow_failure: true
  

############################
# 4️⃣ sonarqube-backend
############################
sonarqube-backend:
  stage: security-scan
  tags:
     - vm
  image: maven:3.8.5-openjdk-17
  needs:
  - job: backend-tests
    artifacts: true
  script: |
    cd backend
    for service in user-service exam-service answer-service course-service api-gateway-service eureka-service; do
      echo "========== Sonar Backend : $service =========="
      cd $service
      mvn verify sonar:sonar $MAVEN_CLI_OPTS \
        -Dsonar.projectKey=$service \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.java.binaries=target/classes \
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
        || echo "Sonar failed for $service"
      cd ..
    done
  allow_failure: true
############################
# 4️⃣ sca-scan-backend
############################
sca-scan-backend:
  stage: security-scan
  tags:
     - vm
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  needs: ["backend-tests"]
  script:
    - mkdir -p reports
    - echo "🛡️ Analyse SCA optimisée avec Trivy..."
    - cd backend
    - |
      for service in api-gateway-service user-service exam-service course-service answer-service; do
        echo "🔍 Scanning $service..."
        # --timeout 20m : laisse le temps au scan de finir
        # --scanners vuln : scanne UNIQUEMENT les vulnérabilités (gain de vitesse 80%)
        # --skip-db-update : évite de retélécharger la DB à chaque tour de boucle
        trivy fs --format template --template "@/contrib/html.tpl" \
          --output "../reports/${service}-sca.html" \
          --severity HIGH,CRITICAL \
          --scanners vuln \
          --timeout 20m \
          $service || true
      done
  artifacts:
    when: always
    paths:
      - reports/
  allow_failure: true

############################
# 5️⃣ SONARQUBE FRONTEND
############################
sonar-frontend:
  stage: security-scan
  tags:
     - vm
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  needs: ["frontend-tests"]
  script:
    - cd frontend
    - |
      sonar-scanner \
        -Dsonar.projectKey=devsecops-frontend \
        -Dsonar.projectName=devsecops-frontend \
        -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA \
        -Dsonar.sources=src \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
        -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
  allow_failure: true
  
############################
# 5️⃣ sca-scan-frontend
############################
sca-scan-frontend:
  stage: security-scan
  tags:
     - vm
  image: node:18-alpine
  needs: ["frontend-tests"]
  script:
    - cd frontend
    - echo "SCA Frontend — Analyse des dépendances NPM (npm audit)"
    - npm ci --legacy-peer-deps
    - npm audit --json > npm-audit-report.json || true
    - npm audit > npm-audit-report.txt || true
    - npm audit --production --audit-level=critical
  artifacts:
    when: always
    paths:
      - frontend/npm-audit-report.json
      - frontend/npm-audit-report.txt
    expire_in: 1 week
  allow_failure: true

opa-gatekeeper-check:
  stage: policy-check
  image: 
    name: openpolicyagent/conftest:latest
    entrypoint: [""]
  tags:
    - vm
  script:
    - echo "🛡️ Vérification OPA..."
    # On génère un rapport au format JSON pour DefectDojo
    - conftest test k8s/*.yaml -p k8s/kubernetes.rego --output json > opa-report.json || true
  artifacts:
    when: always
    paths:
      - opa-report.json
  allow_failure: true # On le laisse en true pour ne pas bloquer tout pendant tes tests
  
############################
# 8️⃣ BUILD backend & PUSH TO REGISTRY (CORRIGÉ)
############################
docker-build-backend:
  stage: docker-build
  tags:
     - vm
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  before_script:
    - until docker info >/dev/null 2>&1; do sleep 5; done
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd backend
    - |
      for service in eureka-service course-service api-gateway-service user-service exam-service answer-service; do
        IMAGE="registry.gitlab.com/devsecopsi-group/devsecops-project/$service:latest"
        echo "🚀 Building $service"
        docker build --pull -t $IMAGE ./$service
        docker push $IMAGE
      done
  
  ############################
# 8️⃣ BUILD frontend & PUSH TO REGISTRY (CORRIGÉ)
############################     
docker-build-frontend:
  stage: docker-build
  tags:
     - vm
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  before_script:
    - until docker info >/dev/null 2>&1; do sleep 5; done
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
  script:
    - cd frontend
    - IMAGE="registry.gitlab.com/devsecopsi-group/devsecops-project/frontend:latest"
    - echo "🚀 Building frontend"
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE
  
############################
# 9️⃣ SCAN DES IMAGES AVEC TRIVY
############################
container_scan:
  stage: docker-scan
  tags:
     - vm
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  needs:
    - docker-build-backend
    - docker-build-frontend

  variables:
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
    TRIVY_TIMEOUT: "10m"

  cache:
    key: trivy-cache
    paths:
      - .trivycache/

  script:
    - mkdir -p reports/
    - |
      REGISTRY="registry.gitlab.com/devsecopsi-group/devsecops-project"

      for service in eureka-service course-service api-gateway-service user-service exam-service answer-service frontend; do
        IMAGE="$REGISTRY/$service:latest"
        echo "🛡️ Scanning $IMAGE..."

        trivy image \
          --username gitlab-ci-token \
          --password $CI_JOB_TOKEN \
          --severity HIGH,CRITICAL \
          --format template \
          --template "@/contrib/html.tpl" \
          --output "reports/${service}-report.html" \
          $IMAGE || true

        trivy image \
          --username gitlab-ci-token \
          --password $CI_JOB_TOKEN \
          --severity HIGH,CRITICAL \
          --format json \
          --output "reports/${service}-report.json" \
          $IMAGE || true
      done

  artifacts:
    when: always
    paths:
      - reports/
    expire_in: 1 week

  only:
    - main

  when: manual
secret-detection:
  stage: security-scan
  tags:
     - vm
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - echo "🔍 Analyse du dépôt à la recherche de secrets..."
    # On scanne tout l'historique du projet
    - gitleaks detect --source . --redact --report-format sarif --report-path gl-secret-report.sarif || true
  artifacts:
    expire_in: 1 week
    reports:
      sast: gl-secret-report.sarif
  allow_failure: true
  
deploy-to-digitalocean:
  stage: deploy-cloud
  tags:
    - vm # Ton runner qui a accès à kubectl et helm
  script:
    - echo "🚀 Déploiement de l'infrastructure et de la sécurité..."
    
    # 1. Appliquer les manifests applicatifs
    - kubectl apply -f k8s/
    
    # 2. Vérifier/Mettre à jour Falco (Runtime Security)
    # 2. Vérifier/Mettre à jour Falco avec lien DefectDojo -> JIRA
    - |
      if ! helm status falco -n falco >/dev/null 2>&1; then
        echo "🚀 Installation de Falco avec lien JIRA..."
        helm install falco falcosecurity/falco -n falco --create-namespace \
          --set falcosidekick.enabled=true \
          --set falcosidekick.webui.enabled=true \
          --set falcosidekick.config.defectdojo.url="${DEFECTDOJO_URL}" \
          --set falcosidekick.config.defectdojo.token="${DEFECTDOJO_TOKEN}" \
          --set falcosidekick.config.defectdojo.productid="1" \
          --set falcosidekick.config.defectdojo.minimumpriority="warning"
      else
        echo "Falco est déjà en cours d'exécution. Mise à jour des règles..."
        helm upgrade falco falcosecurity/falco -n falco --reuse-values \
          --set falcosidekick.config.defectdojo.url="${DEFECTDOJO_URL}" \
          --set falcosidekick.config.defectdojo.token="${DEFECTDOJO_TOKEN}" \
          --set falcosidekick.config.defectdojo.productid="1"
      fi

    # 3. Vérifier/Mettre à jour le Monitoring (Prometheus/Grafana)
    - |
      if ! helm status monitoring -n default >/dev/null 2>&1; then
        echo "Installing Monitoring Stack..."
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install monitoring prometheus-community/kube-prometheus-stack
      else
        echo "Monitoring is already running."
      fi

    # 4. Redémarrage des services pour prendre les nouvelles images
    - kubectl rollout restart deployment/api-gateway-service
    - kubectl rollout restart deployment/user-service
    - kubectl rollout restart deployment/course-service
    - kubectl rollout restart deployment/exam-service
    - kubectl rollout restart deployment/answer-service
    - kubectl rollout restart deployment/frontend
  only:
    - main
owasp-zap-dast:
  stage: dast-scan
  tags:
     - vm
  before_script:
    - mkdir -p /zap/wrk
    - chmod 777 /zap/wrk
  script:
    - echo "🚀 Démarrage des scans DAST sur le Cloud DigitalOcean..."
    - echo "1. Scan de l'API Gateway"
    - docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t http://209.38.187.208 -r zap_gateway_report.html -x zap_gateway_report.xml || true
    - echo "2. Scan du Frontend Angular"
    - docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t http://209.38.187.16 -r zap_frontend_report.html -x zap_frontend_report.xml || true
  artifacts:
    when: always
    paths:
      - "zap_gateway_report.xml"
      - "zap_frontend_report.xml"
      - "zap_gateway_report.html"
      - "zap_frontend_report.html"
    expire_in: 1 week
  allow_failure: true
 
.upload_template: &upload_template
  stage: upload-defectdojo
  image: alpine:latest
  tags:
    - vm
  before_script:
    - apk add --no-cache curl
    - |
      if [ -z "$DEFECTDOJO_URL" ] || [ -z "$DEFECTDOJO_TOKEN" ]; then
        echo "❌ ERROR: DEFECTDOJO_URL ou DEFECTDOJO_TOKEN n'est pas défini dans les variables CI/CD"
        exit 1
      fi

# 1. Push Secrets (Gitleaks)
upload-secrets:
  <<: *upload_template
  needs: ["secret-detection"]
  script:
    - |
      if [ -f "gl-secret-report.sarif" ]; then
        curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
          -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
          -F "active=true" -F "verified=true" -F "push_to_jira=true" \
          -F "scan_type=SARIF" \
          -F "product_name=DevsecopsApp" \
          -F "engagement_name=Pipeline-Full-Scan" \
          -F "file=@gl-secret-report.sarif"
      else
        echo "⚠️ gl-secret-report.sarif introuvable."
      fi

# 2. Push Container Scan (Trivy)
upload-trivy-backend:
  <<: *upload_template
  needs: ["container_scan"]
  script:
    - |
      for file in reports/*-report.json; do
        if [ -f "$file" ]; then
          echo "📤 Upload $file"
          curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
            -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            -F "scan_type=Trivy Scan" \
            -F "product_name=DevsecopsApp" \
            -F "engagement_name=Pipeline-Full-Scan" \
            -F "file=@$file" \
            -F "active=true" -F "verified=true" -F "push_to_jira=true"
        fi
      done

# 3. Push DAST (ZAP XML)
upload-zap-dast:
  <<: *upload_template
  needs: ["owasp-zap-dast"]
  script:
    - |
      for file in *.xml; do
        if [ -f "$file" ]; then
          echo "📤 Uploading $file..."
          curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
            -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            -F "active=true" -F "verified=true" -F "push_to_jira=true" \
            -F "scan_type=ZAP Scan" \
            -F "product_name=DevsecopsApp" \
            -F "engagement_name=Pipeline-Full-Scan" \
            -F "file=@$file"
        fi
      done # Le 'done' ferme la boucle, pas besoin de 'fi' ici si on n'utilise pas de 'if' global

# 4. Push SonarQube
upload-sonarqube:
  <<: *upload_template
  needs: ["sonarqube-backend"]
  script:
    - |
      for service in user-service exam-service answer-service course-service api-gateway-service eureka-service; do
        echo "🚀 Import SonarQube pour $service"
        curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
          -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
          -F "scan_type=SonarQube API Import" \
          -F "product_name=DevsecopsApp" \
          -F "engagement_name=Pipeline-Full-Scan" \
          -F "service=$service" \
          -F "active=true" -F "verified=true" -F "push_to_jira=true"
      done
upload-opa-to-jira:
  <<: *upload_template
  needs: ["opa-gatekeeper-check"]
  script:
    - |
      if [ -f "opa-report.json" ]; then
        echo "📤 Envoi des violations OPA vers JIRA..."
        curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
          -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
          -F "active=true" -F "verified=true" -F "push_to_jira=true" \
          -F "scan_type=Conftest Scan" \
          -F "product_name=DevsecopsApp" \
          -F "engagement_name=Pipeline-Full-Scan" \
          -F "file=@opa-report.json"
      fi    
    