version: "2.0"

gitlab:
  controls:
    # --- GESTION DES IMAGES ---
    containerImageMustNotUseForbiddenTags:
      enabled: true
      tags:
        - latest
        - dev
      # IMPORTANT : On met à "false" car épingler par SHA256 est trop lourd pour un PFE
      containerImagesMustBePinnedByDigest: false

    containerImageMustComeFromAuthorizedSources:
      enabled: true
      trustDockerHubOfficialImages: true 
      trustedUrls:
        - $CI_REGISTRY_IMAGE:*
        - registry.gitlab.com/devsecopsi-group/devsecops-project/*
        - docker.io/*  # Autorise Docker Hub pour Trivy, Sonar, etc.
        - quay.io/*    # Autorise Quay.io

    # --- STRUCTURE DU PIPELINE ---
    # On désactive ce contrôle car tu as 28 jobs "hardcoded" (dans un seul fichier)
    # Cela fera monter ton score immédiatement.
    pipelineMustNotIncludeHardcodedJobs:
      enabled: false

    branchMustBeProtected:
      enabled: true
      defaultMustBeProtected: true
      namePatterns:
        - main
      allowForcePush: false

    # --- SÉCURITÉ DOCKER ---
    pipelineMustNotUseDockerInDocker:
      enabled: true
      detectInsecureDaemon: true # Te préviendra si le TLS est coupé

    # --- AUTRES CONTRÔLES ---
    pipelineMustNotEnableDebugTrace:
      enabled: true
    
    securityJobsMustNotBeWeakened:
      enabled: true
      # On autorise "allow_failure: true" pour ne pas bloquer tes tests
      allowFailureMustBeFalse:
        enabled: false