# Port unique pour le service Course (8081 est souvent pour User, utilise 8082)
server.port=8082
spring.application.name=course-service

# Connexion Base de données (Hostname 'mysql' pour Docker/Kubernetes)
spring.datasource.url=jdbc:mysql://mysql:3306/microservices_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Enregistrement Eureka (Hostname 'eureka-service')
eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
# --- LA SECTION CORS A ÉTÉ SUPPRIMÉE ICI ---
# C'est l'API Gateway qui s'en occupe pour tout le monde