# 1. USER-SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: user-service
        image: registry.gitlab.com/devsecopsi-group/devsecops-project/user-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH # FIX PROMETHEUS 404
          value: "/students/actuator"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/microservices_db
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-service:8761/eureka/
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        resources:
          limits: { memory: "512Mi" }
          requests: { memory: "256Mi" }
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8081
---


# 2. COURSE-SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: course-service
        image: registry.gitlab.com/devsecopsi-group/devsecops-project/course-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH # FIX PROMETHEUS 404
          value: "/courses/actuator"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/microservices_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-service:8761/eureka/
        resources:
          limits: { memory: "512Mi" }
          requests: { memory: "256Mi" }
---

apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course-service
  ports:
    - port: 8082
---


# 3. ANSWER-SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: answer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answer-service
  template:
    metadata:
      labels:
        app: answer-service
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: answer-service
        image: registry.gitlab.com/devsecopsi-group/devsecops-project/answer-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH # FIX PROMETHEUS 404
          value: "/answers/actuator"
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongodb:27017/microservices_answers_db
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-service:8761/eureka/
        resources:
          limits: { memory: "512Mi" }
          requests: { memory: "256Mi" }
---

apiVersion: v1
kind: Service
metadata:
  name: answer-service
spec:
  selector:
    app: answer-service
  ports:
    - port: 8083
---


# 4. EXAM-SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-service
  template:
    metadata:
      labels:
        app: exam-service
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: exam-service
        image: registry.gitlab.com/devsecopsi-group/devsecops-project/exam-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH # FIX PROMETHEUS 404
          value: "/exams/actuator"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/microservices_db
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-service:8761/eureka/
        resources:
          limits: { memory: "512Mi" }
          requests: { memory: "256Mi" }
---

apiVersion: v1
kind: Service
metadata:
  name: exam-service
spec:
  selector:
    app: exam-service
  ports:
    - port: 8084