# 1. Volume pour Postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
# 2. Volume pour MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
# 3. Déploiement Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: microservices_db
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA # On ajoute cette variable
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgre-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres-data # C'est CA qui règle le problème !
      volumes:
      - name: postgre-storage
        persistentVolumeClaim: { claimName: postgres-pvc }
        persistentVolumeClaim: { claimName: postgres-pvc }
---
# 4. Déploiement MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector: { matchLabels: { app: mysql } }
  template:
    metadata: { labels: { app: mysql } }
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: microservices_db
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim: { claimName: mysql-pvc }