apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: frontend
        image: registry.gitlab.com/devsecopsi-group/devsecops-project/frontend:latest
        ports:
        - containerPort: 8080 # 👈 On passe sur un port haut (>1024)
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true # 💡 Bonus : l'expert va adorer ça (immutabilité)
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts: # 💡 Nécessaire si tu mets readOnlyRootFilesystem: true
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer 
  selector:
    app: frontend
  ports:
    - port: 80        # 🌐 L'IP publique reste sur le port 80 pour l'utilisateur
      targetPort: 8080 # 🎯 Mais elle envoie le trafic vers le port 8080 du conteneur