server:
port: 8084
spring:
application:
name: exam-service
datasource:
url: mysql://mysql:3306/db_microservices_exams?createDatabaseIfNotExist=true
username: root
password: root
jpa:
hibernate:
ddl-auto: update
eureka:
client:
service-url:
defaultZone: http://eureka-service:8761/eureka/
register-with-eureka: true
fetch-registry: true
instance:
prefer-ip-address: true
