spring.application.name=answer-service
server.port=8083

# Connexion via le nom du container Docker
spring.data.mongodb.uri=mongodb://mongodb:mongodb@mongodb:27017/microservices_answers_db?authSource=admin

# Configuration Eureka
eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.value}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# --- CONFIGURATION MONITORING (ACTUATOR) ---
# Autorise Prometheus à lire les données du service
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true

# Permet d'avoir des noms de métriques clairs dans Grafana
management.metrics.tags.application=${spring.application.name}